const Vish = require('../');

console.log(Vish.encrypt('test'));
console.log(Vish.decrypt('olllolloolloloooolllolllollllool'));

console.log(Vish.encrypt('some very very long ass string that would probably break 12345'));
console.log(Vish.decrypt('olllolololllooloolllooolollololoooloooooolllooooollollooolllloloolllooooooloooooollollooolllooooolloolloollollooooloooooolllloloolloooooololllloolllloooooloooooollloollolloooooololllllooloooooololllloololllloolollollololooololololololoollolooloooooololloololoollooolooolooolololloooloooooolollooooloollllolololoooloololooloooooloolooooooloolloooloollololoolooloolllolloolllooloollloololoooolooloolllooolooooooollolloolooololoollollloolloolooolllolloolooooooolloooloolloolooolloolloolloloooollolol'));